title: The Lost Memories of Artemis
description: A collection of mysterious tales from the brotherhood of the sigil
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: "dnd_01"
permalink: /stories/:title/
show_downloads: false