title: The Lost Memories of Artemis
description: A collection of mysterious tales from the brotherhood of the sigil
remote_theme: benbalter/retlab
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
baseurl: ""
permalink: /stories/:title/
markdown: kramdown
